### ISSUE TITLE
<foldablelist> tags are being removed after save.

### ISSUE THREAD

**Issue by smccants** [medmen/dokuwiki-plugin-foldablelist#1]
It may be a case that I do not understand how to use this plugin, but it is not working for me the way I expected.

I have source with nested lists.  Below is a snippet:

```
<foldablelist><ul>
	<li class="level1"><a class="wikilink1" href="/dwiki/doku.php?id=itownership" title="itownership">IT Ownership</a></li>
	<li class="level1 node">IT
	<ul>
		<li class="level3"><a class="wikilink2" href="/dwiki/doku.php?id=it_servers" rel="nofollow" title="it_servers">Servers</a></li>
		<li class="level3"><a class="wikilink1" href="/dwiki/doku.php?id=ipmi" title="ipmi">IPMI</a></li>
		<li class="level3 node">Backups
		<ul>
			<li class="level4"><a class="wikilink1" href="/dwiki/doku.php?id=backup_mysql_replication" title="backup_mysql_replication">MySQL Replication</a></li>
			<li class="level4">Running</li>
			<li class="level4"><a class="wikilink1" href="/dwiki/doku.php?id=failover" title="failover">Failover captain/kirk</a></li>
			<li class="level4"><a class="wikilink1" href="/dwiki/doku.php?id=backup_restore" title="backup_restore">Restoring</a></li>
		</ul>
		</li>
       </ul>
</ul></foldablelist>
```
The preview does not show any change and if I save it, I see no change.  When I go back in to edit it, the <foldablelist> tags have been removed.  I also tried the tags around one of the inner lists, but that didn't work either.

Is this not supported or am I doing something wrong?

Thank you.

**Comment by medmen** [comment]
I will try and take a look at your problem.. So far this plugin has been used largely by myself alone, mostly for simple lists...

**Comment by medmen** [comment]
here is why it may not work for you:

1. the list will only hide after a (configurable) amount of items. By default 5 items in list will show up, longer lists will be cut down. You can change the number in admins config page.

I have updated the [readme](https://github.com/medmen/dokuwiki-plugin-foldablelist/blob/master/README.md) to reflect this..

2. As this plugin was hacked with simple lists in mind I was uncertain how it behaves in complex lists like yours. So i put up a test with altered configuration (hide after 3 items).

The result: every list inside the tags is treated equally, items will collapse after 3 entries. This applies to nested lists too.

See the live example at [my test site](https://dokuwiki.humanvisualisierungsknecht.de/doku.php/my-plugins:foldablelist:start#example)

3. I could not reproduce your issue of tags being removed. If this issue persists for your site, please provide some more info (e.g. further plugins installed or different template used)

**Comment by smccants** [comment]
The tags are still disappearing for me.  It may be because we are using Ckgedit and an HTML list (looks very different from the source on your test site).

I looked at what you have set on your test site and I think this solution isn't quite the solution I am looking for.  I'm looking for something more all on the lines of the traditional tree structure (see JavaFX for an example: https://docs.oracle.com/javafx/2/ui_controls/tree-view.htm#BABDEADA).

So, this is something you might not want/need to support.

Thank you for your help.
