### ISSUE TITLE
Plugin manager always reports an update is available for Foldablelist

### ISSUE THREAD

**Issue by smccants** [medmen/dokuwiki-plugin-foldablelist#2]
I installed the plugin and then go to the extension manager and I see:

![image](https://user-images.githubusercontent.com/10539455/73467910-99c94700-4349-11ea-99d3-d93afd578d5c.png)

If I click "Update", it claims to update, but still shows the same version and that an Update is available (see screenshot above).

**Comment by medmen** [comment]
Thanx for reporting. This should be fixed now

**Comment by smccants** [comment]
Can verify that it is working correctly now.  Thanks!
