### ISSUE TITLE
Feature request: collapse after indent level

### ISSUE THREAD

**Issue by gitterspec** [medmen/dokuwiki-plugin-foldablelist#9]
Great plugin. It would be great to be able to configure only certain indent levels to be collapsed. For example, I don't want top level bullets to be folded. Maybe that would correspond with `collapse_after_level=1` with the default being 0.

In my use case, I would set `collapse_after=0` and `collapse_after_level=` 1, 2, or 3 depending on the page.

**Comment by medmen** [comment]
I did a few tests, results look promising.
But I will need a bit of time to adapt the whole plugin..
